name: Java CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build and deploy:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build using Maven
        run: mvn clean package

      - name: Deployment
        runs: |
          echo "Deploying Application..."
          
